function isit=GTDefined(filename_sequence_basename_frames_or_video)

isit= ( isfield(filename_sequence_basename_frames_or_video,'gtbasename') &...
    isfield(filename_sequence_basename_frames_or_video,'gtnumber_format') &...
    isfield(filename_sequence_basename_frames_or_video,'gtclosure') &...
    isfield(filename_sequence_basename_frames_or_video,'gtstartNumber') &...
    isfield(filename_sequence_basename_frames_or_video,'bgcode') &...
    isfield(filename_sequence_basename_frames_or_video,'mbcode') );