function Setthepath()

path(path,'Cluster');
path(path,'UCM');
path(path,['UCM',filesep,'Aggregation']);
% path(path,['UCM',filesep,'Aggregation',filesep,'Auxclustering']);
path(path,['UCM',filesep,'Aggregation',filesep,'Appearance']);
path(path,['UCM',filesep,'Aggregation',filesep,'Appearance',filesep,'Mex']);
path(path,['UCM',filesep,'Aggregation',filesep,'Auxfunctions']);
path(path,['UCM',filesep,'Aggregation',filesep,'Auxfunctions',filesep,'Fileops']);
path(path,['UCM',filesep,'Aggregation',filesep,'Auxfunctions',filesep,'Toycases']);
% path(path,['UCM',filesep,'Aggregation',filesep,'Auxfunctions',filesep,'Statistics']);
path(path,['UCM',filesep,'Aggregation',filesep,'Benchmarkbm']);
path(path,['UCM',filesep,'Aggregation',filesep,'Benchmarkcm']);
path(path,['UCM',filesep,'Aggregation',filesep,'Benchmarkev']);
path(path,['UCM',filesep,'Aggregation',filesep,'Calibration']);
path(path,['UCM',filesep,'Aggregation',filesep,'Higherorder']);
path(path,['UCM',filesep,'Aggregation',filesep,'Includehigherorder']);
path(path,['UCM',filesep,'Aggregation',filesep,'Metricmerging']);
path(path,['UCM',filesep,'Aggregation',filesep,'Quantitative']);
path(path,['UCM',filesep,'Aggregation',filesep,'Longterm']);
path(path,['UCM',filesep,'Aggregation',filesep,'Intraframesimilarities']);
path(path,['UCM',filesep,'Aggregation',filesep,'Occlusionlongterm']);
path(path,['UCM',filesep,'Aggregation',filesep,'Proplabels']);
path(path,['UCM',filesep,'Aggregation',filesep,'Relevance']);
path(path,['UCM',filesep,'Aggregation',filesep,'Relevance',filesep,'Kasp']);
path(path,['UCM',filesep,'Aggregation',filesep,'Shortterm']);
path(path,['UCM',filesep,'Aggregation',filesep,'Shortterm',filesep,'Mex']);
path(path,['UCM',filesep,'Aggregation',filesep,'Velocitysimilarities']);
path(path,['UCM',filesep,'Aggregation',filesep,'Velocitysimilarities',filesep,'Mex']);
path(path,['UCM',filesep,'Auxclustering']);
path(path,['UCM',filesep,'Auxclustering',filesep,'Minimumspanningtree']);
path(path,['UCM',filesep,'Auxclustering',filesep,'Minimumspanningtree',filesep,'Kruskalandgui']);
path(path,['UCM',filesep,'Auxclustering',filesep,'Ap']);
path(path,['UCM',filesep,'Auxfunctions']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Activecontours']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Auxauxfunctions']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Dp']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Dp',filesep,'Otherdp']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Treeoftrajectories']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Learningtrajectoryselection']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Litekmeans']);
% path(path,['UCM',filesep,'Auxfunctions',filesep,'lightspeed']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Netlab',filesep,'netlab3_3']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Netlab',filesep,'nethelp3_3']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Ochs']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Piotr_mtoolbox_v251']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Piotr_mtoolbox_v251',filesep,'classify']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Piotr_mtoolbox_v251',filesep,'matlab']);
% path(path,genpath(['UCM',filesep,'Auxfunctions',filesep,'Piotr_mtoolbox_v251',filesep,'classify']));
% path(path,genpath(['UCM',filesep,'Auxfunctions',filesep,'Piotr_mtoolbox_v251',filesep,'external']));
% path(path,genpath(['UCM',filesep,'Auxfunctions',filesep,'Piotr_mtoolbox_v251',filesep,'images']));
% path(path,genpath(['UCM',filesep,'Auxfunctions',filesep,'Piotr_mtoolbox_v251',filesep,'matlab']));
% path(path,genpath(['UCM',filesep,'Auxfunctions',filesep,'Piotr_mtoolbox_v251',filesep,'filters']));
path(path,['UCM',filesep,'Auxfunctions',filesep,'Qualitative']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'RF_Class_C']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Svx']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'TVL1']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'VBEMGMM']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'VLToolbox']);
path(path,['UCM',filesep,'Auxfunctions',filesep,'Yael']);
path(path,['UCM',filesep,'Clustering']);
path(path,['UCM',filesep,'Clustering',filesep,'Density']);
path(path,['UCM',filesep,'Clustering',filesep,'Icm']);
path(path,['UCM',filesep,'Clustering',filesep,'Mcl']);
path(path,['UCM',filesep,'Clustering',filesep,'Occamlocalclustering']);
path(path,['UCM',filesep,'Clustering',filesep,'Occamlocalclustering',filesep,'SetPartFolder']); %aux of Occamlocalclustering
path(path,['UCM',filesep,'Clustering',filesep,'Selftuningsc']);
path(path,['UCM',filesep,'Detectanddescribe']);
path(path,['UCM',filesep,'Detectanddescribe',filesep,'Edges']);
path(path,['UCM',filesep,'Detectanddescribe',filesep,'SCV']);
path(path,['UCM',filesep,'Detectanddescribe',filesep,'SCV',filesep,'Scvauxfunctions']);
path(path,['UCM',filesep,'Discriminant']);
path(path,['UCM',filesep,'Discriminant',filesep,'Bestcomputedvectors']);
path(path,['UCM',filesep,'Discriminant',filesep,'Auxdiscriminantfunctions']);
path(path,['UCM',filesep,'Discriminant',filesep,'Newdiscriminant']);
path(path,['UCM',filesep,'Discriminant',filesep,'Newdiscriminant',filesep,'Optimised']);
path(path,['UCM',filesep,'Distancematrixcomputation']);
path(path,['UCM',filesep,'Distancematrixcomputation',filesep,'Onrequestds']);
path(path,['UCM',filesep,'Fileoperations']);
path(path,['UCM',filesep,'Flow']);
path(path,['UCM',filesep,'Flow',filesep,'Flofiles']);
path(path,['UCM',filesep,'Fourieranalysis']);
% path(path,['UCM',filesep,'Graphcut']);
path(path,['UCM',filesep,'Isomap']);
path(path,['UCM',filesep,'Labelpropagation']);
path(path,['UCM',filesep,'Laplacian']);
path(path,['UCM',filesep,'Onrequest']);
path(path,['UCM',filesep,'Otherfunctions']);
path(path,['UCM',filesep,'Otherfunctions',filesep,'Auxwarping']);
path(path,['UCM',filesep,'Otherfunctions',filesep,'Groundtruthmake']);
path(path,['UCM',filesep,'Meanshiftclustering']);
path(path,['UCM',filesep,'Pmatrix']);
path(path,['UCM',filesep,'Segmentation']);
path(path,['UCM',filesep,'Segmentation',filesep,'Addtobenchmark']);
path(path,['UCM',filesep,'Segmentation',filesep,'Benchmark']);
path(path,['UCM',filesep,'Segmentation',filesep,'Benchmark',filesep,'Auxbenchmark']);
path(path,['UCM',filesep,'Segmentation',filesep,'Lib']);
% path(path,['UCM',filesep,'Segmentation',filesep,'Benchmark',filesep,'Benchmarks']);
% path(path,['UCM',filesep,'Segmentation',filesep,'Videodatasetbench']);

